# Generated by Django 4.2.5 on 2023-09-09 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_dependent', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('wife', models.BooleanField()),
                ('parents', models.PositiveIntegerField()),
                ('age_range_a', models.PositiveIntegerField()),
                ('age_range_b', models.PositiveIntegerField()),
                ('girl_child_a', models.BooleanField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_loan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education_loan_interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dis_lvl_a', models.PositiveIntegerField()),
                ('dis_lvl_b', models.PositiveIntegerField()),
                ('exp_med_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exp_med_b', models.DecimalField(decimal_places=2, max_digits=10)),
                ('list_investments', models.TextField()),
                ('exp_invest_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invest_nps', models.BooleanField()),
                ('exp_invest_nps', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sec_80c', models.BooleanField()),
                ('sec_80ccc', models.BooleanField()),
                ('sec_80ccd_1b', models.BooleanField()),
                ('sec_80gg', models.BooleanField()),
                ('sec_80e', models.BooleanField()),
                ('sec_80d', models.BooleanField()),
                ('sec_80dd', models.BooleanField()),
                ('sec_80ddb', models.BooleanField()),
                ('sec_80u', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
